/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication5;


import java.awt.Component;
import java.util.*;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gulraiz
 */

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
   static String user_input;
   static int board[][]=new int[4][4];
   static int comp_row;
   static int comp_col;
   static String comp_string;
   static ArrayList<JButton> data=new ArrayList<>();
   static List<Descion> decide_move=new ArrayList<>();
   static int row=0;
   static int col=0;
   int total_count=0;
    
    
    
     
   
    public NewJFrame() {
        
        
        initComponents();
        
        
    }
     {
       
       //if (c instanceof JLabel)
         //((JLabel)c).setText("hi");
         
        
         //add_data();
         //getcomponent(0);
       
         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setForeground(new java.awt.Color(0, 204, 153));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setForeground(new java.awt.Color(0, 255, 204));

        jButton1.setText("-");
        jButton1.setAutoscrolls(true);
        jButton1.setBorderPainted(false);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setOpaque(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("-");
        jButton2.setAutoscrolls(true);
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jButton4.setText("-");
        jButton4.setAutoscrolls(true);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("-");
        jButton5.setAutoscrolls(true);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("-");
        jButton6.setAutoscrolls(true);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("-");
        jButton7.setAutoscrolls(true);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("-");
        jButton8.setAutoscrolls(true);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("-");
        jButton9.setAutoscrolls(true);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setText("-");
        jButton10.setAutoscrolls(true);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.setText("-");
        jButton11.setAutoscrolls(true);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton12.setText("-");
        jButton12.setAutoscrolls(true);
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton13.setText("-");
        jButton13.setAutoscrolls(true);
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        jButton14.setText("-");
        jButton14.setAutoscrolls(true);
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton14MouseEntered(evt);
            }
        });

        jButton15.setText("-");
        jButton15.setAutoscrolls(true);
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        jButton16.setText("-");
        jButton16.setAutoscrolls(true);
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });

        jButton3.setText("-");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Name:");

        {
            //jButton1=new JButton();
            data.add(jButton1);
            data.add(jButton2);
            data.add(jButton3);
            data.add(jButton4);
            data.add(jButton5);
            data.add(jButton6);
            data.add(jButton7);
            data.add(jButton8);
            data.add(jButton9);
            data.add(jButton10);
            data.add(jButton11);
            data.add(jButton12);
            data.add(jButton13);
            data.add(jButton14);
            data.add(jButton15);
            data.add(jButton16);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(198, 396, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
   
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        change(jButton1,user_input,0,0);
    }//GEN-LAST:event_jButton1MouseClicked
       
    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        
        
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        //data.add(jButton2);
        change(jButton2,user_input,0,1);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       change(jButton3,user_input,0,2);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        change(jButton4,user_input,0,3);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
         change(jButton5,user_input,1,0);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        change(jButton6,user_input,1,1);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        change(jButton7,user_input,1,2);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
       change(jButton8,user_input,1,3);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
       change(jButton9,user_input,2,0);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
         change(jButton10,user_input,2,1);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
       change(jButton11,user_input,2,2);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
         change(jButton12,user_input,2,3);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        change(jButton13,user_input,3,0);
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseEntered
       
    }//GEN-LAST:event_jButton14MouseEntered

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
       change(jButton15,user_input,3,2);
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        change(jButton16,user_input,3,3);
    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        change(jButton14,user_input,3,1);
    }//GEN-LAST:event_jButton14MouseClicked
   //My functions
    //1 for user
    //2 for computer
    void change(JButton j,String m,int row,int col){
        if(j.getText().contains("-")){
            j.setText(m);
            board[row][col]=1;
            total_count++;
             computer_move();
             
        }
        else
            JOptionPane.showMessageDialog(j, "This Cell is Already used");
       
       
    }
    void computer_move(){
        row=-1;col=-1;
        int flag=0;
       check_horizontal(decide_move);
        check_vertical(decide_move);
        check_first_diagnol(decide_move);
        check_second_diagnol(decide_move);
        Collections.sort(decide_move);
        int i=0;
       
        
        row=decide_move.get(0).row;
        col=decide_move.get(0).col;
       
        
        
        
        
            if(row>-1){
            int j=row*4+col;
            System.out.println(decide_move.get(0).name);
            System.out.println(row);
            System.out.println(col);
            System.out.println("priority: "+decide_move.get(0).priority);
            
            
            
            if(j>=0&&total_count<16&&board[row][col]==0){
                board[row][col]=2;
                comp_row=row;
                comp_col=col;
                total_count++;
            data.get(j).setText(comp_string);
            }
            }
            else if(total_count<16)
            {
                check_horizontal(decide_move);
                row=decide_move.get(0).row;
                col=decide_move.get(0).col;
                int p=row*4+col;
                 if(p>=0&&total_count<16&&board[row][col]==0){
                board[row][col]=2;
                comp_row=row;
                comp_col=col;
                total_count++;
            data.get(p).setText(comp_string);
            }
                
                
              System.out.println("ab tu la gaye na");
              
            }
            if(decide_move.get(0).priority==4){
                JOptionPane.showMessageDialog(this, "Computer Wins");
            }
            else if(total_count>=15){
                JOptionPane.showMessageDialog(this, "Draw");
               
            }
            
        
       
    
    }
    void check_win(){
        
    }
    int check_horizontal(List<Descion> p){
        int i=0,j=0,count_user=0,count_comp=0,total_count=0,flag=0,u_r=0,u_c=0,c_r=0,c_c=0;
        int first=0,second=0,win_con=0,temp_row=-1,temp_col=-1;
         p.get(0).name="Horizontal";
         p.get(0).priority=-1;
        while(i<4){
            j=0;
            count_user=0;//changed
            count_comp=0;//changed
            first=0;
            second=0;
            while(j<4){
                if(board[i][j]==1){
                    count_user++;
                    total_count++;
                }
                if(board[i][j]==2){
                    count_comp++;
                    total_count++;
                }
               if(board[i][j]==0){
                   temp_row=i;
                   temp_col=j;
               }
                j++;
            }
           
            if(count_user>3){
                p.get(0).row=-1;
                 p.get(0).col=-1;
                p.get(0).priority=5;
                return 1;
            }
            if(count_comp>3){
                p.get(0).row=u_r;
                 p.get(0).col=u_c;
                p.get(0).priority=6;
                return 2;
            }
            if((count_user==3||count_user==2)&&count_comp==0){
                j=0;
                flag=1;
                while(j<4){
                    if(board[i][j]==0&&first==0){
                        first=1;
                        u_r=i;
                        u_c=j;
                        p.get(0).row=u_r;
                        p.get(0).col=u_c;
                        p.get(0).priority=3;
                        
                    }
                    j++;
                }
                //count_user=0;//change
                //first=0;
            }
            if(count_comp==3){
                j=0;
                flag=2;
                while(j<4){
                    
                    if(board[i][j]==0&&second==0){
                        second=1;
                        c_r=i;
                        c_c=j;
                        win_con=1;
                        
                    }
                    j++;
                }
                if(win_con==1){
                    p.get(0).row=c_r;
                    p.get(0).col=c_c;
                    p.get(0).priority=4;
                    row=c_r;
                    col=c_c;
                    return 2;
                }
                //count_user=0;//change
                //second=0;
            }
            if(count_comp>=1&&second==0&&first==0&&count_user==0&&flag!=1){
                 j=0;
                flag=2;
                while(j<4){
                    
                    if(board[i][j]==0&&second==0){
                        second=1;
                        c_r=i;
                        c_c=j;
                        p.get(0).row=c_r;
                        p.get(0).col=c_c;
                        p.get(0).priority=2;
                        
                    }
                    j++;
                }
                
            }
            else if(count_comp==0&&second==0&&first==0&&count_user==0&&flag==0){
                 j=0;
                flag=2;
                while(j<4){
                    
                    if(board[i][j]==0&&second==0){
                        second=1;
                        c_r=i;
                        c_c=j;
                        p.get(0).row=c_r;
                        p.get(0).col=c_c;
                        p.get(0).priority=1;
                        
                    }
                    j++;
                }
                
            }
            if(p.get(0).priority==-1&&temp_row>-1){
                 p.get(0).row=temp_row;
                        p.get(0).col=temp_col;
                        p.get(0).priority=0;
            }
            
            
            i++;
        }
        if(flag==1){
            row=u_r;
            col=u_c;
            return 0;
            
        }
        if(flag==2){
           // int m=check_vertical();
           /* if(m==4);
            else*/{
            row=c_r;
            col=c_c;
            }
            return 0;
        }
         if(total_count==16){
               p.get(0).row=-1;
                 p.get(0).col=-1;
                p.get(0).priority=5;
                return 3;
            }
        return -1;
    }
    int check_vertical(List<Descion> p){
       int i=0,j=0,count_user=0,count_comp=0,total_count=0,flag=0,u_r=0,u_c=0,c_r=0,c_c=0;
       int first=0,second=0,win=0;
       p.get(1).name="Vertical";
       p.get(1).priority=-1;
        while(i<4){
            j=0;
            count_user=0;
            count_comp=0;
            first=0;
            second=0;
            while(j<4){
                if(board[j][i]==1){
                    count_user++;
                    total_count++;
                }
                if(board[j][i]==2){
                    count_comp++;
                    total_count++;
                }
                
                
               
                j++;
            }
            if(count_user>3){
                p.get(1).row=-1;
                 p.get(1).col=-1;
                p.get(1).priority=5;
                return 1;
            }
            if(count_comp>3){
                p.get(1).row=-1;
                 p.get(1).col=-1;
                p.get(1).priority=6;
                return 2;
            }
            if((count_user==3||count_user==2)&&count_comp==0){
                j=0;
                flag=1;
                while(j<4&&first==0){
                    if(board[j][i]==0){
                        first=1;
                        u_r=j;
                        u_c=i;
                        p.get(1).row=u_r;
                        p.get(1).col=u_c;
                        p.get(1).priority=3;
                        
                    }
                    j++;
                }
               // first=0;
                
            }
            if(count_comp==3&&second==0){
                j=0;
                flag=2;
                while(j<4&&second==0){
                    
                    if(board[j][i]==0){
                        second=1;
                        c_r=j;
                        c_c=i;
                        win=1;
                        
                    }
                    j++;
                }
                if(win==1){
                       p.get(1).row=c_r;
                        p.get(1).col=c_c;
                        p.get(1).priority=4;
                    row=c_r;
                    col=c_c;
                    return 2;
                }
                
                //second=0;
            }
             if(count_comp>=1&&second==0&&first==0&&count_user==0&&flag!=1){
                 j=0;
                flag=2;
                while(j<4){
                    
                    if(board[j][i]==0&&second==0){
                        second=1;
                        c_r=j;
                        c_c=i;
                        p.get(1).row=c_r;
                        p.get(1).col=c_c;
                        p.get(1).priority=2;
                        
                    }
                    j++;
                }
                
            }
            else if(count_comp==0&&second==0&&first==0&&count_user==0&&flag==0){
                 j=0;
                flag=2;
                while(j<4){
                    
                    if(board[j][i]==0&&second==0){
                        second=1;
                        c_r=j;
                        c_c=i;
                        p.get(1).row=c_r;
                        p.get(1).col=c_c;
                        p.get(1).priority=1;
                        
                    }
                    j++;
                }
                
            }
            i++;
        }
        if(flag==1){
            row=u_r;
            col=u_c;
            return 4;
            
        }
        if(flag==2){
            row=c_r;
            col=c_c;
            return 0;
        }
        
        
        return -1;
    }
    int check_first_diagnol(List<Descion> p){
        int i=0,j=0,comp_count=0,user_count=0;
        int ro=-1,cl=-1;
        p.get(2).name="first";
        p.get(2).priority=-1;
        while(i<4){
            if(board[i][j]==1){
                user_count++;
                
            }
           if(board[i][j]==2){
                comp_count++;
                
            }
           else if(board[i][j]==0)
            {
                
                ro=i;
                cl=j;
            }
            i++;
            j++;
                
        }
       if((user_count==2||user_count==3)&&comp_count==0){
           p.get(2).row=ro;
           p.get(2).col=cl;
           p.get(2).priority=3;
           
            
            
        }
       if(comp_count==3&&user_count==0){
            p.get(2).row=ro;
           p.get(2).col=cl;
           p.get(2).priority=4;
           
       }
      else if(comp_count>=1&&user_count==0){
           p.get(2).row=ro;
           p.get(2).col=cl;
           p.get(2).priority=2;
       }
      else if(comp_count==0&&user_count==0){
            p.get(2).row=ro;
           p.get(2).col=cl;
           p.get(2).priority=1;
       }
       
        if(user_count>3){
            p.get(2).row=-1;
                 p.get(2).col=-1;
                p.get(2).priority=5;
            return 1;
        }
        else if(comp_count>3){
            p.get(2).row=-1;
                 p.get(2).col=-1;
                p.get(2).priority=6;
            return 2;
        }
        return 0;
        
         
    }
    int check_second_diagnol(List<Descion> p){
         int i=0,j=3,comp_count=0,user_count=0,first=0;
         int ro=-1,cl=-1;
         p.get(3).name="Second";
         p.get(3).priority=-1;
        while(i<4){
            if(board[i][j]==1){
                user_count++;
            }
            if(board[i][j]==2){
                comp_count++;
            }
            else if(board[i][j]==0)
            {
                
                ro=i;
                cl=j;
            }
            i++;
            j--;
                
        }
        if((user_count==2||user_count==3)&&comp_count==0){
           p.get(3).row=ro;
           p.get(3).col=cl;
           p.get(3).priority=3;
           
            
            
        }
       if(comp_count==3&&user_count==0){
            p.get(3).row=ro;
           p.get(3).col=cl;
           p.get(3).priority=4;
           
       }
      else if(comp_count>=1&&user_count==0){
           p.get(3).row=ro;
           p.get(3).col=cl;
           p.get(3).priority=2;
       }
      else if(comp_count==0&&user_count==0){
            p.get(3).row=ro;
           p.get(3).col=cl;
           p.get(3).priority=1;
       }
        else if(user_count>3){
            return 1;
        }
        else if(comp_count>3){
            return 2;
        }
        
        
        return 0;
    }
        
   
    
    void getcomponent(int m){
       // Component c=jPanel1.getComponent(4);
       //data.get(1).setText("X");
       
       //System.out.println(no);
        /*if(c instanceof JButton){
            System.out.println("name");
             ((JButton) c).setText("+");
        }*/
       
    }
    
     
       
    /**
     * @param args the command line arguments
     */
    static class option{
          
        String takeinput(){
           String[] options = { "0", "X"};
           String input = (String) JOptionPane.showInputDialog(null, 
        "What symbol you want to choose?",
         "Symbol Select",
        JOptionPane.QUESTION_MESSAGE, 
        null, 
        options, 
        options[0]);
           return input;
              
        }
    }
    public static  void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        option p1=new option();
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
        
       
        //intialize();
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                JFrame j=new NewJFrame();
                        j.setVisible(true);
                        j.setTitle("Tic Tac Toe");
                String inp=JOptionPane.showInputDialog("Enter Name");
                       System.out.println(inp);
                       String lab="Name: "+inp;
                        user_input= p1.takeinput();
                      if(user_input.contains("0")){
                            comp_string="X";
                          }
                         else
                     comp_string="0";
                      
                            jLabel2.setText(lab);
                           comp_row=(int) (Math.random() * 4);
                         comp_col=(int)(Math.random()*4);
                         board[comp_row][comp_col]=2;
                    int num=(comp_row*4)+comp_col;
                      data.get(num).setText(comp_string);
                      decide_move.add(new Descion());
                      decide_move.add(new Descion());
                      decide_move.add(new Descion());
                      decide_move.add(new Descion());
                
            }
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    public javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private static javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
